# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tamano', models.CharField(max_length=15, verbose_name=b'Tamano de animal')),
                ('sexo', models.CharField(max_length=10, verbose_name=b'Sexo')),
                ('raza', models.CharField(blank=True, default=b'NA', max_length=60, verbose_name=b'Raza de animal')),
                ('perdido', models.BooleanField(default=False)),
                ('descripcion', models.CharField(default=b'NA', max_length=100, verbose_name=b'Descripcion')),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('direccion1', models.CharField(max_length=60)),
                ('direccion2', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30, verbose_name=b'Nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name=b'Apellido')),
                ('usuario', models.CharField(max_length=20, verbose_name=b'username')),
                ('contrasena', models.CharField(max_length=20, verbose_name=b'password')),
                ('celular', models.CharField(max_length=10, verbose_name=b'Telefono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.direccion'),
        ),
    ]
